### ISSUE TITLE
10k Apart deploy issue

### ISSUE THREAD

**Issue by aarongustafson** [johno/fc#23]
Unfortunately, we can’t deploy your project because our build of Node doesn’t support async/await. You can use Babel to transpile it and we will be able to accept and deploy the entry, but if you can’t do that, we’ll (sadly) need to reject it :-(

According to @molant, Babel gan auto-magically transpile on `require` statements. It’s definitely not my area of expertise, but he says it can be done & I trust him :-)

**Comment by johno** [comment]
Not a problem @aarongustafson, I've created another branch [here](https://github.com/johnotander/fc/tree/no-async) that no longer uses `async`/`await`. Hopefully that branch will work in the build environment. Please let me know if you encounter any other issues.

Thank you!

**Comment by molant** [comment]
@johnotander now there are more issues. From what I'm seeing you have a build step and Azure Webapps doesn't support that OOB. Best solution will be to commit the dist folder with your output.

Thanks

**Comment by johno** [comment]
Hey @molant. Glad to hear it's all fixed! I've added another commit to the `no-async` branch that includes `dist/index.js`. Please let me know if you encounter any other issues.

Thank you!

**Comment by molant** [comment]
@johnotander working now. I also had to change the listening port to 

```
process.env.PORT || 3000
```
